server:
  port: 5038

spring:
  rabbitmq:
    addresses: localhost
  cloud:
    aws:
      endpoint: http://localhost:19000

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028
    network-modification-server:
      base-uri: http://localhost:5007
    filter-server:
      base-uri: http://localhost:5027
